// Package render presents a Report in the format the user asked for: a styled
// terminal verdict card, plain text, Markdown, or JSON. All formats are derived
// from the same Report, so the numbers never disagree across outputs.
package render

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/agenticraptor/readme-radar/internal/humanize"
	"github.com/agenticraptor/readme-radar/internal/report"
)

// Format selects an output renderer.
type Format string

const (
	FormatTerm     Format = "term"
	FormatPlain    Format = "plain"
	FormatMarkdown Format = "markdown"
	FormatJSON     Format = "json"
)

// Options controls rendering.
type Options struct {
	Format  Format
	NoColor bool
}

// Render returns the report rendered in the requested format.
func Render(rep report.Report, opt Options) (string, error) {
	switch opt.Format {
	case FormatJSON:
		b, err := json.MarshalIndent(rep, "", "  ")
		return string(b), err
	case FormatMarkdown:
		return markdown(rep), nil
	case FormatPlain:
		return card(rep, false), nil
	case FormatTerm, "":
		return card(rep, !opt.NoColor), nil
	default:
		return "", fmt.Errorf("unknown format %q (use term, plain, markdown, or json)", opt.Format)
	}
}

// markdown renders a shareable Markdown report.
func markdown(rep report.Report) string {
	var b strings.Builder
	s := rep.Score
	fmt.Fprintf(&b, "# readme-radar verdict: %s — grade %s (%d/100)\n\n", rep.Target.Slug(), s.Grade, s.Overall)
	fmt.Fprintf(&b, "> **%s.** %s\n\n", titleCase(string(s.Verdict)), s.Headline)
	if rep.Target.URL != "" {
		fmt.Fprintf(&b, "[%s](%s)\n\n", rep.Target.URL, rep.Target.URL)
	}

	b.WriteString("| Axis | Grade | Score |\n|------|:-----:|------:|\n")
	for _, a := range s.Axes {
		fmt.Fprintf(&b, "| %s | %s | %d |\n", a.Name, a.Grade, a.Score)
	}
	b.WriteString("\n")

	if rep.Narrative.Summary != "" {
		fmt.Fprintf(&b, "%s\n\n", rep.Narrative.Summary)
		for _, bl := range rep.Narrative.Bullets {
			fmt.Fprintf(&b, "- %s\n", bl)
		}
		if len(rep.Narrative.Bullets) > 0 {
			b.WriteString("\n")
		}
	}

	b.WriteString("## Key facts\n\n")
	if rep.Repo.FullName != "" {
		fmt.Fprintf(&b, "- **Repository:** %s — %s stars, %d contributors, %d releases\n",
			rep.Repo.FullName, humanize.Count(rep.Repo.Stars), rep.Repo.Contributors, rep.Repo.Releases)
		fmt.Fprintf(&b, "- **Last commit:** %s · **License:** %s · **Language:** %s\n",
			ageOf(rep), dash(rep.Repo.License), dash(rep.Repo.PrimaryLang))
	}
	if rep.Size.Known {
		fmt.Fprintf(&b, "- **Install size:** %s unpacked, %d direct dependencies (%s)\n",
			humanize.Bytes(rep.Size.InstallBytes), rep.Size.DirectDeps, rep.Size.Source)
	}
	if len(rep.Permissions.InstallScripts) > 0 {
		fmt.Fprintf(&b, "- **⚠ Install scripts:** `%s`\n", strings.Join(rep.Permissions.InstallScripts, "`, `"))
	}
	b.WriteString("\n")

	writeMDFactors(&b, "Maintenance", rep.Health.Factors)
	writeMDFactors(&b, "Telemetry", rep.Telemetry.Factors)
	writeMDFactors(&b, "Permissions", rep.Permissions.Capabilities)
	writeMDFactors(&b, "Footprint", rep.Size.Factors)

	if len(rep.Warnings) > 0 {
		b.WriteString("## Notes\n\n")
		for _, w := range rep.Warnings {
			fmt.Fprintf(&b, "- %s\n", w)
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "---\n_Generated by [readme-radar](https://github.com/agenticraptor/readme-radar) · narrative: %s_\n", rep.Narrative.Source)
	return b.String()
}

func writeMDFactors(b *strings.Builder, title string, fs []report.Factor) {
	if len(fs) == 0 {
		return
	}
	fmt.Fprintf(b, "### %s\n\n", title)
	for _, f := range fs {
		fmt.Fprintf(b, "- %s **%s** — %s\n", mdSymbol(f.Level), f.Name, f.Detail)
	}
	b.WriteString("\n")
}

func mdSymbol(l report.Level) string {
	switch l {
	case report.LevelGood:
		return "✅"
	case report.LevelWarn:
		return "⚠️"
	case report.LevelBad:
		return "🛑"
	default:
		return "•"
	}
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func dash(s string) string {
	if s == "" || s == "none" {
		return "—"
	}
	return s
}
